# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CanvasCV
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  CanvasCV is an OpenCV GUI framework for simple user ineraction. It works
  inside the OpenCV native windows. It provides interactive shapes and widgets
  in a non intrusive design.
baseurl: "/CanvasCV" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sagi-z

environment: production
#environment: development
google_analytics: UA-102191827-1
#google_seo: "true"
# url is taken from site.github.url, which is fine
#webmaster_verifications:
#  google: JUx4WnitKgBv-bkQtPcA5t8KpbzedlCc0FHHLhac9J0
#  bing: A8ABC38B72560EE52E9985C1E21C5BE4
logo: /CanvasCV/assets/img/project_logo.jpg

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
